### ISSUE TITLE
Feature Request - add modals to the portfolio like those in the Freelancer theme

### ISSUE THREAD

**Issue by digitalcraftsman** [BlackrockDigital/startbootstrap-creative#10]
They would be a nice addition because a single picture doesn't say very much about a project.

**Comment by davidtmiller** [comment]
I'll be adding some sort of modal or lightbox to the thumbnails in the next build, thanks for the request.

**Comment by digitalcraftsman** [comment]
Thanks for your repsonse. I've already implemented the modal myself based on one of your other themes. By the way: I've [ported](https://github.com/digitalcraftsman/hugo-creative-theme) to the [Hugo](https://gohugo.io/).
