### ISSUE TITLE
Problem with background photo in the front page

### ISSUE THREAD

**Issue by pang007** [BlackrockDigital/startbootstrap-creative#101]
I am using python 3.6 and django version 2.0.2.

When i incorporate the code into my app, the first page background is always missing (hence in white color). Others photos/ icons are just all fine.

Can anyone help?

**Comment by davidtmiller** [comment]
Make sure the file path is correct, or load the image from a URL on a CDN which will give you a direct path. The relative path might have changed when you ported things into a new framework, so make sure the file paths (and file names) are correct.
