### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by thomascarpenter21** [BlackrockDigital/startbootstrap-creative#102]
All the dependencies will not load. Dependencies include bootstrap, jquery, footawesome, etc..
My research shows that its a permission issue. How can i gain permission from a forked repo?

**Comment by davidtmiller** [comment]
Once forked it is your own repo so you should have permission. Make sure you're logged in with whatever you're using to make changes whether it's the GitHub Desktop Client or terminal.
