### ISSUE TITLE
Issue with Ad-Blockers

### ISSUE THREAD

**Issue by petramika** [BlackrockDigital/startbootstrap-creative#121]
Hi, I am using this amazing template for a personal project, but, I find that when navigating through it, suddenly it jumps to top and the navigation bar goes transparent (I  leave an OK image and an image with the issue).

![1](https://user-images.githubusercontent.com/6030217/46551012-e5471e80-c8d6-11e8-9bff-35e53153eef9.png)
![2](https://user-images.githubusercontent.com/6030217/46551013-e5471e80-c8d6-11e8-9eee-e5d48513e60f.png)

To "fix" it, I had to disable adblock and popup blockers, weird. In order to avoid disabling this, I had to remove at the CSS (creative.css/creative.min.css) the following beginning lines:

```
body,
html {
  width: 100%;
  height: 100%;
}
```

Hope it helps to anyone with same problem.

A.

**Comment by davidtmiller** [comment]
I think this is now fixed, I have been testing it with adblock running and it seems to be working now.
