### ISSUE TITLE
How do you change a stroke color of hamburger icon?

### ISSUE THREAD

**Issue by asterisk37n** [BlackrockDigital/startbootstrap-creative#126]
I noticed
```background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.5)```
shows a hamburger icon, but Is it possible to change three stroke colors?

**Comment by davidtmiller** [comment]
https://stackoverflow.com/questions/42586729/bootstrap-4-change-hamburger-toggler-color/42587673
