### ISSUE TITLE
'npm start' deletes the vendor folder and no changes in scss are registered with gulp 

### ISSUE THREAD

**Issue by altback** [BlackrockDigital/startbootstrap-creative#144]
After 'npm install' when I use command 'npm start', it deletes the 'vendor' folder.
I think it should have been back using 'function modules()' in gulpfile.js.

Also, any changes made to scss are not reflected to either of 'creative.css' or 'creative.min.css' file.

**Comment by altback** [comment]
I checked this problem with both windows 10 and ubuntu 18.04 LTS. And this happens in both OS.

However, this doesn't happen with MacOS X. Does this issue has something to do with fsevents?

**Comment by altback** [comment]
I tried to again on Centos7 and it didn't work properly. What makes it work on Mac OS?

**Comment by davidtmiller** [comment]
I am not sure on this one, I will have to test it on some different machines. The vendor directory gets cleaned on purpose and rebuilt, but the SCSS not compiling is certainly not intended.

**Comment by jlea-sysops** [comment]
This sounds akin to what I am experiencing on my MacBook. No changes I make to the CSS file are kept when running NPM Start

**Comment by altback** [comment]
Yes, I understand that vendor directory is cleaned on purpose. 
Only issue I faced is the cross-platform compatibility issue.

**Comment by ajcastro** [comment]
@davidtmiller can we just put the vendor folder in .gitignore?

**Comment by finevine** [comment]
Hi, when runing `gulp` or `gulp css`, no css is compiled

**Comment by davidtmiller** [comment]
In the v6 build I am working on, `vendor` is getting removed for good and I am moving to CDN's for third party resources. I'm also dropping Gulp as a dependency and using npm scripts instead of Gulp to handle compiling. For that reason I am going to close this for the time being since running gulp tasks and having a vendor directory will no longer be part of this theme.
