### ISSUE TITLE
Too little vertical margin in the Contact section in mobile 

### ISSUE THREAD

**Issue by apaatsio** [BlackrockDigital/startbootstrap-creative#151]
There is too little vertical margin between the Contact section elements on mobile resolutions.

See how the envelope icon is almost touching the phone number. There should be more margin between those elements.

![bootstrap_template_margin_issue](https://user-images.githubusercontent.com/195210/55966525-db80e800-5c78-11e9-8ecf-e0478e776f97.png)

Version: 5.1.4
Browser: Chrome 75 with resolution set to "iPhone X" from dev tools

**Comment by davidtmiller** [comment]
Fixed in #155 - thanks for pointing this out!
