### ISSUE TITLE
Is it possible using the template with reactjs?

### ISSUE THREAD

**Issue by Nieto2018** [BlackrockDigital/startbootstrap-creative#160]
Hello,

As the title say, i would like know whether is possible using the template with reactjs and how, whether it is possible.

Thanks

**Comment by davidtmiller** [comment]
This theme isn't built to work out of the box with any framework in particular, but you can certainly chop up the HTML and CSS and bring the styling into React.

**Comment by Nieto2018** [comment]
ok, thanks @davidtmiller
