### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by yourwpmadesimple** [BlackrockDigital/startbootstrap-creative#163]
Hello,  I am wondering if you can help me with this issue being thrown here? 

```
Uncaught TypeError: Cannot read property 'top' of undefined
    at navbarCollapse (creative.js?ver=5.1.7:31)
    at creative.js?ver=5.1.7:38
    at creative.js?ver=5.1.7:58
```
I have googled myself into a migraine and have not found an answer on how to solve this. I appreciate any help. 

Thank you!
Wayne

**Comment by davidtmiller** [comment]
If you're removing the click to scroll functionality from the HTML then you will be getting this error. You can get rid of the click to scroll stuff in the JS and you won't get this error any more.
