### ISSUE TITLE
Find Out More border color when clicked

### ISSUE THREAD

**Issue by t55jk7op** [BlackrockDigital/startbootstrap-creative#172]
I cannot change the orange color when the button is clicked. I already changed all the orange colors in the css and is still there.

Any help will be gratefull, thank you!

**Comment by davidtmiller** [comment]
This color would be darker than the orange color you see on the button. You can change the colors in the SCSS and recompile, or you can search for the `.btn-primary` class in the CSS and manually replace border color to something different.
