### ISSUE TITLE
scrollSpy is not a function

### ISSUE THREAD

**Issue by super-iterator** [BlackrockDigital/startbootstrap-creative#21]
Getting this error:

Uncaught TypeError: $(...).scrollSpy is not a function      creative.js:20

Uncaught TypeError: Cannot read property 'classList' of null  classie.js:36

How to get over it??

**Comment by davidtmiller** [comment]
I need to remove classie.js and cbpAnimatedHeader.js because this theme doesn't use it.

**Comment by super-iterator** [comment]
So, if I remove them I'm good to go?
