### ISSUE TITLE
not working on iphone

### ISSUE THREAD

**Issue by alex283** [BlackrockDigital/startbootstrap-creative#24]
hello
the live preview works fine however the 1.0.2 available for download (so is the version available on github) does not work on iphone. works well on any other device. 
any clue?
thanks

**Comment by davidtmiller** [comment]
I'll have to look into this, I'm not able to replicate any bugs on iPhone but I'll check again.

**Comment by alex283** [comment]
just got to the bottom of it, it works fine on iphone as long as I dont use a transparent redirection... which I did. (for some reason it prevents ios safari webkit from getting the browser size). 
note that even with a transparent redirection (and using 100vh instead of 100% and/or using min-height:500 px here and there) it can work too. 
will need to configure my dns properly.
anyway thank you, love the theme!
