### ISSUE TITLE
Button not centering on all display widths

### ISSUE THREAD

**Issue by enoyes767** [BlackrockDigital/startbootstrap-creative#25]
Upon adding a button to this section of the theme, the button is correctly centered in my preview window, but if I extend it just a bit or to full width, it jumps to the left. I've tried but I cannot get it to work for the life of me.

![screen shot 2016-03-16 at 7 13 31 pm](https://cloud.githubusercontent.com/assets/17892004/13833410/40bb8226-ebab-11e5-9d80-5d8a87a32cfb.png)
![screen shot 2016-03-16 at 7 13 42 pm](https://cloud.githubusercontent.com/assets/17892004/13833411/40d41a16-ebab-11e5-9f6e-ad6d4e504a00.png)

**Comment by RedSparr0w** [comment]
It is due to having the class "col-lg-4" on the button/a element which makes it center on 1/3 of the page or 4/12 of the columns

**Comment by RedSparr0w** [comment]
It is due to having the class "col-lg-4" on the div which makes it center on 1/3 of the page or 4/12 of the columns

**Comment by enoyes767** [comment]
What will I need to change it to for it to stay aligned? Removing that simply makes it go to the right of the text at full width.

**Comment by enoyes767** [comment]
I figured it out, thank you very much for pointing out the issue!
