### ISSUE TITLE
jQuery Easing Plugin

### ISSUE THREAD

**Issue by abirone** [BlackrockDigital/startbootstrap-creative#43]
When I turn on SSL, I get the error;
Mixed Content: The page at 'https://anthonybirone.com/#contact' was loaded over HTTPS, but requested an insecure script 'http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'. This request has been blocked; the content must be served over HTTPS.

You guys need to have a way to detect if page is loaded in HTTPS or not and alter the script string based on that.

**Comment by davidtmiller** [comment]
I am now loading any CDN's over HTTPS with this theme, and I'll be checking others as well. This is fixed in this theme now, instead of having a script detecting HTTPS I am just going to load everything over HTTPS if it's an external library.
