### ISSUE TITLE
Changing Orange Color

### ISSUE THREAD

**Issue by OTSP** [BlackrockDigital/startbootstrap-creative#50]
Hi love your theme am just having trouble changing the orange to a green color.

Have spent 3 days on it to no avail.

Could you please assist.

Kindest regards

Aaron

**Comment by Obs-Dev** [comment]
You should be able to change all styling colors in the creative.css file. Be sure to change the reference in your html to creative.css rather than creative.min.css.

**Comment by OTSP** [comment]
Thank you so much Did that little change and everything worked
