### ISSUE TITLE
Changing Orange on Hover Color

### ISSUE THREAD

**Issue by OTSP** [BlackrockDigital/startbootstrap-creative#51]
Can you please advise how I change the on hover orange over the portfolio images?

Kindest regards

Aaron

**Comment by Obs-Dev** [comment]
The color displayed when hovering over a portfolio image is inherited from the background property of the '.portfolio-box .portfolio-box-caption' class of the css (creative.css). You may wish to become more familiar with your browser's advanced functionality (i.e. Chrome's Dev Tools - https://developer.chrome.com/devtools) to more easily find the css objects being referenced.

**Comment by OTSP** [comment]
Great thankyou havent been using chrome but found where to change the background colour in css thank you.
