### ISSUE TITLE
SUGGESTION for JS change.

### ISSUE THREAD

**Issue by lohe** [BlackrockDigital/startbootstrap-creative#52]
Hei,

First: nice template. Create job :)

I do have one suggestion due to fact how Silverstripe CMS handles certain things. In js/creative(.min).js file
Row 8:
`scrollTop: ($($anchor.attr('href')).offset().top - 50)`
I would replace with
`scrollTop: ($($anchor.attr('href').substring($anchor.attr('href').indexOf("#"))).offset().top - 50)`

Or to make it more simple, Row 6 I would change from
`var $anchor = $(this);`
to
`var $anchor = $(this).attr('href');`
and then  row 8 would be:
`scrollTop: ($($anchor.substring($anchor.indexOf("#"))).offset().top - 50)`

The reason is to make sure the anchor+name (for example #about) is forced to use. In Silverstripe all hrefs automatically get / in front of ANY URL. Meanwhile, it will work on any system anyways, due to the fact that return is always #+name (#about).

Of course - second option is to change template and js to use some other custom attribute, like data-value or any other similar.

**Comment by davidtmiller** [comment]
This is a pretty specialized change for a single case use scenario. This is a good addition or fix for people using Silverstripe and other similar CMS solutions, but I am going to keep it as is for now.
