### ISSUE TITLE
None of the css files are working

### ISSUE THREAD

**Issue by byLEVIATHAN** [BlackrockDigital/startbootstrap-creative#54]
I have been using this template for a project im working on. And the css wasn't working and a few days ago the css started working, like everything I changed actually starting showing. But today none of the css files are working again.  (I deleted everything out of all the css files and my page still showed all the css)

P.S. I was wondering which of the css files I need to use, because there are multiple files)

Thanks in advance,

I

**Comment by bnunruh** [comment]
I've been having problems too. It works fine with the files on my local machine, but not at all on my github hosted page

**Comment by visvisuals** [comment]
Same here. Forked the template, changed nothing and the css files are not loading, accessing directly gives 404 error, but I see them in the repo. So, so confusing!

**Comment by bnunruh** [comment]
I was reading on another templates issues and they figured it out. I changed the vendor folder name to lib then had to change all of the vendor instances to lib in the index file, that's it! Works perfectly again!

**Comment by visvisuals** [comment]
Wow, thanks a million, I thought I was getting crazy! Works perfectly.. almost. Still some bugs in the element inspector console, but at least the CSS works.

**Comment by davidtmiller** [comment]
What sort of front end framework are you using to get this bug? I will be renaming all of the vendor folders in a future build, but I am just curious about where you're getting this bug.

**Comment by visvisuals** [comment]
Uh.. just hosting it here, on GitHub, I guess? I'm not really a framework-and-stuff savvy guy, I just followed the instructions for using the template on GH and that's all I can help you with. Thanks for the beautiful template, by the way!

**Comment by rkrockstar** [comment]
After changing the folder name of the folder 'vendor', there are still some bugs. For example, the alignment is not correct and I can't see the navigation bar. What should I do?

**Comment by kylemh** [comment]
It is imperative that you link the Bootstrap.css first, then the creative.css file, and then any other style sheet after that. 

Order matters with stylesheets, so if you're using Gulp or Grunt, be sure to do your script in that order. If you're just hard-coding the stylesheet's into your html header, be sure they go from top to bottom in the order I just described.

**Comment by davidtmiller** [comment]
In the next build `vendor` is going to be changed to `lib` so hopefully that will help moving into Bootstrap 4

I'm sure there will be conflicts with `lib` vs. `vendor` but it seems to me that `lib` is going to be the better choice moving forward.

 Closing this for now.
