### ISSUE TITLE
Menu changes when I change the height of navbar

### ISSUE THREAD

**Issue by mshaynerush** [BlackrockDigital/startbootstrap-creative#59]
I changed the min-height of the navbar from 50px to 100px. the menu then collapses no matter what screen size i'm on. Then, I change it back to 50px, the menu stays collapsed. what??

**Comment by davidtmiller** [comment]
The navbar is being overhauled in Bootstrap 4 which is going to be the next release, and since the height of the navbar isn't manipulated in the Bootstrap 3 version of this theme I'm going to assume this is a Bootstrap 3 or custom CSS issue on the user-end. Closing this one.
