### ISSUE TITLE
sticky footer

### ISSUE THREAD

**Issue by timaschew** [BlackrockDigital/startbootstrap-creative#71]
Thank you for the great theme.
I was trying to add ad sticky footer for the cookie notification bar but these styles seems not to work

```
html {
  min-height:100%;
  position:relative;
}
body {
  margin-bottom:60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  background-color: #f5f5f5;
}
```

If I remove the `position:relative` from the `html` it's at the footer but not sticky.

**Comment by davidtmiller** [comment]
Absolute positioned elements position themselves based on their closest parent with relative positioning.
