### ISSUE TITLE
How to add images to gallery categories in the portfolio section?

### ISSUE THREAD

**Issue by wolpertinger1980** [BlackrockDigital/startbootstrap-creative#75]
Gallery section (portfolio): How do I configure the gallery to show images per categories only? Currently the gallery shows all images from all categories and not only the one that the user selects. How to make the gallery working to only show the pictures from a specific category and not all pictures from all categories? Any feedback is highly appreciated....

**Comment by davidtmiller** [comment]
You could make different instances of a gallery. I'd check out the magific popup plugin's docs to figure out how to add more galleries and customize their galleries.
