### ISSUE TITLE
Collapse conflict

### ISSUE THREAD

**Issue by srccd** [BlackrockDigital/startbootstrap-creative#80]
In v4, it appears the scrolling effect in creative.js is conflicting with the bootstrap collapse feature. In the current commit of Creative, collapse works with button tags, but not anchor tags, since it utilizes the # urls too.

It appears to be caused by this new method in creative.js:
`$('a[href*="#"]:not([href="#"])').click(function() {`

**Comment by davidtmiller** [comment]
Should be fixed in #77

**Comment by srccd** [comment]
Still seems to be failing. I admit I could be missing something, but if I try to add a simplistic accordion/collapse, it doesn't work - even with a fresh d/l of gh-pages.
`<h4><a data-toggle="collapse" data-parent="#accordion" href="#collapse1">test question? &raquo;</a></h4><div id="collapse1" class="panel-collapse collapse"><p>test answer!</p></div>`

Removing the "Smooth scrolling using jQuery easing" segment in the creative.js gets it working again.

**Comment by srccd** [comment]
Changing the line I referenced in the original post above to something like the following resolves the issue.
`$('a[href*="#"]:not([href="#"], [data-toggle="collapse"])').click(function() {`

**Comment by davidtmiller** [comment]
Thanks for bringing this up again. Your solution works for just the collapse conflict, but this will still conflict with a lot of other things, including modals and anything else that is targeting an id through a link.

I think the only way to truly fix this up with no conflicts is to add a class to all page scrolling triggers and then adjust the JS accordingly. So, for example, all navigation links that currently look like this:

`<a class="nav-link" href="#target">Link</a>`

will need to change to something like this:

`<a class="nav-link js-scroll-trigger" href="#services">Services</a>`

with the JS changing from this:

`$('a[href*="#"]:not([href="#"])').click(function() {`

to this:

`$('a.js-scroll-trigger[href*="#"]:not([href="#"])').click(function() {`

I feel like this is the only real solution to the scroll triggers not interfering with anything. I'd love to not use a special JS only class, but I'm afraid this is the only way I know how to prevent conflicts.

**Comment by davidtmiller** [comment]
Fixed in the latest commit, I'll make the pr to the gh-pages branch once a few more updates have been made.

**Comment by davidtmiller** [comment]
Fixed in #83 - closing this one out!
