### ISSUE TITLE
How do you get this file to deploy on Heroku

### ISSUE THREAD

**Issue by vbchick712** [BlackrockDigital/startbootstrap-creative#88]
This is probably a n00b question, but I've been working with your template and trying to get it deploy on Heroku and I can't get it to deploy. Heroku detects it as a Node.js file but all of the documentation on deploying a Node.js file on Heroku does not sync with what you have so I figured you have a simple fix on how to get it to deploy. It needs a server.js or Procfile...is this something only Heroku requires or can I get this to deploy elsewhere easily? Thanks!

**Comment by demoklion** [comment]
Hey, also noob here :) I seem to have been in your situation. 

1. I've just used what [heroku suggests](https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-a-procfile) and created a simple file `/Procfile` in the root of your project with contents
 ```web: node index.js```

2. Then I added a file `index.js` with following contents (which I can't remeber where I've copied from):
```
const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
    .use(express.static(path.join(__dirname, 'public')))
    .set('views', path.join(__dirname, 'public'))
    .set('view engine', 'html')
    .get('/', (req, res) => res.render('public'))
    .listen(PORT, () => console.log(`Listening on ${ PORT }`))
```

3. and you should be good to go to continue in the guide.

**Comment by davidtmiller** [comment]
@demoklion thanks for the update. I have no idea really - I just work HTML/CSS 😬
