### ISSUE TITLE
Change image source for the gallery

### ISSUE THREAD

**Issue by billardesign** [BlackrockDigital/startbootstrap-creative#89]
I'm currently trying to changes the contents of the image gallery to different images as well as create another popup that will display a div containing an Iframe and text underneath.

How would I go about changing the magnific-popup to allow for such things??

Kind Regards

**Comment by davidtmiller** [comment]
I would take a look at the magnific popup docs. http://dimsemenov.com/plugins/magnific-popup/

They do allow text, forms, and other content for the popups (other than just images). That's a good place to start!
