### ISSUE TITLE
Top menu (Scrollspy) problem with Firefox

### ISSUE THREAD

**Issue by prassaschr** [BlackrockDigital/startbootstrap-creative#92]
Hi.
If you try the demo with a browser other than Chrome you 'll notice that there is a problem with the top menu  (Scrollspy).
I you play a little with that you will see that if you click on the "Services" the "About" href will be active, or if you click on the "Portfolio" the previous one will be active.
Anyway... something is going on with the active top menu.

Thank you.

**Comment by prassaschr** [comment]
I think I found a solution to the problem...
In the creative.js and creative.min.js
Change the **offset from 48 to 60** in both files:
Now the behavior is the same in all browsers. Please check it for your self

// Activate scrollspy to add active class to navbar items on scroll
  $('body').scrollspy({
    target: '#mainNav',
    **offset: 48**
  });

**Comment by davidtmiller** [comment]
Thanks for posting this, I just pushed an update with some user-submitted scrollbar fixes so I'll mark this resolved!
