### ISSUE TITLE
Help with font icons

### ISSUE THREAD

**Issue by MartinMil** [BlackrockDigital/startbootstrap-creative#98]
Hi how are you? i'm having problems to show the font icons when the page is already uploaded. 
In my localhost its everything ok:
![image](https://user-images.githubusercontent.com/11871210/33786276-3e62b47a-dc47-11e7-8a2a-eff1c279a9ce.png)
But when it's online it doesn't show the icons and the console says something like "slow network" blabla
![image](https://user-images.githubusercontent.com/11871210/33786318-7004f5ce-dc47-11e7-8f81-2f8c18ebb9ff.png)
Your help is really valuable for me!
Gracias! Saludos! :)

**Comment by davidtmiller** [comment]
This looks like an issue with the Font Awesome 4 library. It seems the icons aren't loading due to slow network behavior. It might be a browser thing as well.
